files:
  - source: README.md
    translation: /translations/%two_letters_code%.S%original_file_name%
    update_option : update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: '123'
